"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.dailyAnalyticsRollup = exports.onReviewCreate = exports.requestDownload = exports.paypalWebhook = exports.cashfreeWebhook = exports.onUserRoleChange = exports.onUserCreate = void 0;
const app_1 = require("firebase-admin/app");
(0, app_1.initializeApp)();
var auth_1 = require("./auth");
Object.defineProperty(exports, "onUserCreate", { enumerable: true, get: function () { return auth_1.onUserCreate; } });
var users_1 = require("./users");
Object.defineProperty(exports, "onUserRoleChange", { enumerable: true, get: function () { return users_1.onUserRoleChange; } });
var webhooks_1 = require("./webhooks");
Object.defineProperty(exports, "cashfreeWebhook", { enumerable: true, get: function () { return webhooks_1.cashfreeWebhook; } });
Object.defineProperty(exports, "paypalWebhook", { enumerable: true, get: function () { return webhooks_1.paypalWebhook; } });
var downloads_1 = require("./downloads");
Object.defineProperty(exports, "requestDownload", { enumerable: true, get: function () { return downloads_1.requestDownload; } });
var reviews_1 = require("./reviews");
Object.defineProperty(exports, "onReviewCreate", { enumerable: true, get: function () { return reviews_1.onReviewCreate; } });
var analytics_1 = require("./analytics");
Object.defineProperty(exports, "dailyAnalyticsRollup", { enumerable: true, get: function () { return analytics_1.dailyAnalyticsRollup; } });
